### PR TITLE
Relative folder #12

### PR DESCRIPTION
**Pull request by elisei**

### CODE REVIEW

**Comment by volodymyr-lisniak** [comment]
@elisei 
Can you provide a description for this PR? 
In what case do you have a situation with a path without `pub/` folder?

---------------------------------
Full path to the `loader-1.gif` (for example)
`https://hostname.loc/pub/static/version1584090826/frontend/<package>/<theme>/en_US/images/loader-1.gif`

And the relative path is `pub/static/version1584090826/frontend/<package>/<theme>/en_US/images/loader-1.gif` because *critical CSS* styles is situated in the root of the site `https://hostname.loc/`

**Comment by elisei** [comment]
Sure, @bobmotor 

When accessing, for example, https: //dev.localhost/women/tops-women.html (sample data) or even https: //dev.localhost/checkout/cart/ in addition the file path must not contain the "pub" being just "static / ..."

**Comment by volodymyr-lisniak** [comment]
Yeah, you are right. 
We have the wrong relative path for the different pages because of a different base path.

`https://hostname.loc/men/pub/static/` `!==`
`https://hostname.loc/women/pub/static/`

I think we can fix this with absolute path implementation.

It would be nice if you test this realization #15.

**Comment by elisei** [comment]
Hi @bobmotor 

using "/pub" in urls is not correct. You need 2 calls to the same file when the css is loaded.
In addition, the absolute path can cause problems for stores that do not use ssl in all requests (which is not my case).

**Comment by bobmotor** [comment]
Hi, @elisei!
Sorry for the late reply.

> using "/pub" in urls is not correct. You need 2 calls to the same file when the css is loaded.

The browser will cache the image (for example) the first time it loads, so any subsequent use of the same image will be loaded from the cache instead of from the server.
And I don't  understand how to avoid `pub/` if we have it in our static files path.

> In addition, the absolute path can cause problems for stores that do not use ssl in all requests (which is not my case).

I think we can move this config to `local.js`
```
module.exports = {
    hostname: 'hostname',
    useHttp2: true
};
```

**Pull request closed without merging**
